name: Release New Version

#
# This action builds, tests, and releases new versions of gab.
#

on:
  push:
    branches: [ "main" ]

env:
  version: 0.1.0
  GH_TOKEN: ${{ github.token }}

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check for existing tag
        continue-on-error: true
        id: tag_check
        run: git ls-remote --tags | grep '${{ env.version }}' 

      # Create a release if we didn't find an existing tag
      - name: Create Release
        if: ${{ steps.tag_check.outcome == 'failure' }}
        run:  gh release create -R '${{ github.repository }}' '${{ env.version }}' --generate-notes

  build_artifacts:
    runs-on: ubuntu-latest
    needs: create_release

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        os:
          - macos-none
          - linux-gnu
          - windows-gnu

    steps:
    - uses: actions/checkout@v4

    # TODO: Pin this Gab release
    - name: Setup Gab
      run: |
        curl -L -f https://github.com/gab-language/cgab/releases/latest/download/gab-release-x86_64-linux-gnu -o gab
        chmod +x gab
        ./gab get -n -y -t '${{ matrix.arch }}-${{ matrix.os }}'
        ./gab info

    - name: Build release
      run: |
        ./gab build -t '${{ matrix.arch }}-${{ matrix.os }}' -m github.com/gab-language/cgab@0.1.2 gwordle@${{ env.version }}

    - name: Build release
      run: |
        gh release upload -R '${{ github.repository }}' '${{ env.version }}' 'gwordle@${{env.version}}-cgab-0.1.2-${{ matrix.arch }}-${{ matrix.os }}.exe' || exit 0
